build:
  services:
    mariadb: 10
    elasticsearch: 6.4.2
  image: default-bionic
  environment:
    php: 8.3
  dependencies:
    before:
    override:
      - 'cp .env.scrutinizer .env'
      - 'composer install'
  nodes:
    analysis:
      tests:
        override:
          -
            command: 'php-scrutinizer-run'
filter:
  excluded_paths:
    - "resources/*"
    - "storage/*"
    - "resources/views/themes/*"
    - "public/assets/*"
    - "public/*"
    - "database/*"
    - "docker/*"
    - "config/*"
    - "bootstrap/*"
    - "docs/*"
    - "tests/*"
  dependency_paths:
    - "vendor/*"

checks:
  php:
    code_rating: true
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
      order_alphabetically: true
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    fix_identation_4spaces: true
    fix_doc_comments: true

tools:
  sensiolabs_security_checker: true
  php_analyzer: true
  php_cs_fixer: true
  php_code_sniffer:
    config:
      standard: PSR2
