version: '3.8'

services:
  web: &web
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ./:/site
      - ./docker/.zsh_history:/root/.zsh_history
      - ./docker/.zsh_history:/home/nntmux/.zsh_history
      - ./docker/.mytop:/home/nntmux/.mytop
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/supervisor.d:/etc/supervisor.d
      - ./docker/composer-auth.json:/home/nntmux/.composer/auth.json
      - ./docker/php-overrides.ini:/etc/php/conf.d/overrides.ini
      - ./docker/php-overrides.local.ini:/etc/php/conf.d/overrides.local.ini
    env_file: .env
    ports:
      - 80
    environment:
      IS_DOCKER: "true"
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      TZ: ${APP_TZ}

  tmux:
    <<: *web
    stdin_open: true
    tty: true
    environment:
      IS_DOCKER: "true"
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      TZ: ${APP_TZ}
      COLUMNS: "`tput cols`"
      LINES: "`tput lines`"
    command: /site/cli/docker tmux-start
