name: Laravel

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: TEST
          MYSQL_USER:
          MYSQL_PASSWORD:
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: gd, intl, memcached, sodium
        composer: v2

    - uses: actions/checkout@v3

    - name: Copy environment file
      run: cp .env.example .env

    - name: Install Dependencies
      run: composer install --prefer-dist --no-interaction --no-progress

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: TEST
      run: |
        mkdir -p /home/runner/work/newznab-tmux/newznab-tmux/tests/Unit
        mkdir -p /home/runner/work/newznab-tmux/newznab-tmux/tests/build/logs
        vendor/bin/phpunit
